### ISSUE TITLE
add a STOCeps Galaxy tools

### ISSUE THREAD

**Issue by yvanlebras** [yvanlebras/Galaxy-E#3]
Task for the "wrap" day of the European Galaxy Developer training session. Corresponding [raw script](https://github.com/yvanlebras/Galaxy-E/tree/master/raw_scripts/STOC_bird_temporal_tendency)

**Comment by bgruening** [comment]
Aja!

**Comment by yvanlebras** [comment]
Not an easy script to begin.... sorry @ThimotheeV ;) This script search for input data into `/donnees/` and write outputs into `/Resultats/` and `/Incertain/`.

Parameters are:

- listSp: specify a list of species / specification d'une liste d'espece pour ne pas analyser toutes les especes du jeu de donnees
- id_session: specify an ID / specification d'un id à la session de calcul (NOT TO ASK TO GALAXY USER?)
- annees: specify a vector of first and last year to consider / vecteur de la premiere et derniere annees si toutes les annees presentes dans le jeu de donnees ne doivent pas être prises en compte
- estimateAnnuel: compute species abundance variation / calculer les variations d'abondances des espèces
- ICfigureGroupeSp: display confidence intervals / afficher les intervalles de confiances sur la figure pas groupes de specialisations
- figure:  create figures / creer les figures
- concatFile: concatenate output files and treat them independantly / concatener les fichiers presents dans le dossier donnees et les analyser independamment
- description:  display a simple graph on each panels / avoir un graphique simple sans les deux panels de description des données brutes
- tendance sur graphique: display tendancy text / afficher la tendance en texte sur les graphiques
- tendanceGroupSpe: compute groups indicators / calculer les indicateurs groupes de specialisations

**Comment by yvanlebras** [comment]
@ThimotheeV You can see the [deseq2](https://github.com/galaxyproject/tools-iuc/blob/master/tools/deseq2/deseq2.R) Galaxy integration example. Notably, you surely have to consider the `setup R error handling to go to stderr`, `not crash galaxy with an UTF8 error` and the `get options through commandArgs(TRUE)` cmd lines....

**Comment by yvanlebras** [comment]
Regarding the requirements, I found some conda packages:

- [lme4](https://anaconda.org/mro/r-lme4)
- [arm](https://anaconda.org/mittner/r-arm)
- [ggplot2](https://anaconda.org/bioconda/r-ggplot2)

So you can delete the Rscript correspondng lines:
```
### Verification de l'instalation des packages et instalation des manquants
### necessite une connexion internet
ip <- installed.packages()[,1]
vecPackage <-  c("lme4","arm","ggplot2")
for(p in vecPackage)
    if (!(p %in% ip))
        install.packages(pkgs=p,repos = "http://cran.univ-lyon1.fr/")
```

**Comment by yvanlebras** [comment]
An example datafile (CSV)
[Testdata.txt](https://github.com/yvanlebras/Galaxy-E/files/710935/Testdata.txt)
